<?php

declare(strict_types=1);

namespace SpomkyLabs\PwaBundle\Service;

use Symfony\Component\Asset\Context\ContextInterface;

/**
 * Prepends the base path to the public URLs generated by the bundle.
 *
 * Every URL handled by the bundle (favicons, manifest, service worker, Workbox files, …) is relative to
 * the document root because it is also the path the file is written to. When the application is not served
 * from the root of the domain, e.g. https://example.com/my-project/, those URLs must be prefixed with the
 * base path, exactly like the ones returned by the Asset component.
 *
 * The base path comes from the current request when there is one, and falls back to the base URL of the
 * router request context (i.e. `framework.router.default_uri`) when the assets are compiled from the CLI.
 */
final readonly class BasePathResolver
{
    public function __construct(
        private null|ContextInterface $context = null,
    ) {
    }

    /**
     * The base path, without any trailing slash. An empty string when the application is served from the
     * root of the domain.
     */
    public function getBasePath(): string
    {
        if ($this->context === null) {
            return '';
        }

        return rtrim($this->context->getBasePath(), '/');
    }

    /**
     * Prefixes a URL generated by the bundle with the base path. Absolute URLs, protocol-relative URLs and
     * relative paths are returned unchanged.
     */
    public function prefix(string $url): string
    {
        $basePath = $this->getBasePath();
        if ($basePath === '' || ! str_starts_with($url, '/') || str_starts_with($url, '//')) {
            return $url;
        }

        return $basePath . $url;
    }
}
