<?php

declare(strict_types=1);

namespace SpomkyLabs\PwaBundle\Tests\Unit\ServiceWorkerRule;

use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;
use ReflectionClass;
use SpomkyLabs\PwaBundle\Dto\ServiceWorker;
use SpomkyLabs\PwaBundle\Dto\Workbox;
use SpomkyLabs\PwaBundle\Service\ServiceWorkerBuilder;
use SpomkyLabs\PwaBundle\ServiceWorkerRule\WorkboxHelpers;
use Symfony\Component\DependencyInjection\Attribute\AsTaggedItem;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;

/**
 * @internal
 */
final class WorkboxHelpersTest extends TestCase
{
    #[Test]
    public function itReturnsEmptyStringWhenWorkboxIsDisabled(): void
    {
        // Given
        $workbox = new Workbox();
        $workbox->enabled = false;

        $rule = $this->createRule($workbox);

        // When
        $result = $rule->process();

        // Then
        static::assertSame('', $result);
    }

    /**
     * These helpers cannot be replaced by a plain listener in the application source:
     * they either arbitrate an order between rules generated by the bundle, or carry a
     * state shared between them.
     */
    #[Test]
    #[DataProvider('dataMandatoryHelpers')]
    public function itEmitsTheHelpersTheApplicationCannotReplace(string $helper): void
    {
        // Given
        $workbox = new Workbox();
        $workbox->enabled = true;

        $rule = $this->createRule($workbox);

        // When
        $result = $rule->process();

        // Then
        static::assertStringContainsString($helper, $result);
    }

    /**
     * @return iterable<string, array{string}>
     */
    public static function dataMandatoryHelpers(): iterable
    {
        // Ordered by ClearCache (0), SkipWaiting (5), OfflineFallback (10) and the
        // cache strategies (100). Concurrent native listeners would break that.
        yield 'registerInstallTask' => ['function registerInstallTask(callback, priority = 100) {'];
        yield 'precacheResources' => ['function precacheResources('];
        // Shared with ClearCache, which only purges the names registered here.
        yield 'registerCacheName' => ['function registerCacheName('];
        yield 'openCache' => ['async function openCache('];
        // Read by ClearCache too, to let the application contribute its own caches.
        yield 'registerClearCacheListener' => ['function registerClearCacheListener('];
        // Emitted by the WorkboxPlugin classes.
        yield 'statusGuard' => ['function statusGuard('];
        yield 'createBackgroundSyncPlugin' => ['function createBackgroundSyncPlugin('];
        yield 'createBackgroundSyncPluginWithBroadcast' => ['function createBackgroundSyncPluginWithBroadcast('];
    }

    /**
     * Counterpart of the workbox-window registration injected by PwaRuntime. It no
     * longer goes through registerMessageTask, which moved to the deprecated helpers.
     */
    #[Test]
    public function itHandlesTheSkipWaitingMessageWithoutTheDeprecatedTaskRegistry(): void
    {
        // Given
        $workbox = new Workbox();
        $workbox->enabled = true;

        $rule = $this->createRule($workbox);

        // When
        $result = $rule->process();

        // Then
        static::assertStringContainsString("self.addEventListener('message', (event) => {", $result);
        static::assertStringContainsString("event.data?.type !== 'SKIP_WAITING'", $result);
        static::assertStringContainsString('self.clients.claim()', $result);
        static::assertStringNotContainsString('registerMessageTask', $result);
    }

    /**
     * Guards against a helper silently coming back: they belong to
     * WorkboxDeprecatedHelpers, which the application can switch off.
     */
    #[Test]
    #[DataProvider('dataDeprecatedHelpers')]
    public function itNoLongerEmitsTheDeprecatedHelpers(string $helper): void
    {
        // Given
        $workbox = new Workbox();
        $workbox->enabled = true;

        $rule = $this->createRule($workbox);

        // When
        $result = $rule->process();

        // Then
        static::assertStringNotContainsString($helper, $result);
    }

    /**
     * @return iterable<string, array{string}>
     */
    public static function dataDeprecatedHelpers(): iterable
    {
        yield 'registerCacheFirst' => ['registerCacheFirst'];
        yield 'registerMessageTask' => ['registerMessageTask'];
        yield 'openBackgroundFetchDatabase' => ['openBackgroundFetchDatabase'];
        yield 'registerBackgroundFetchTask' => ['registerBackgroundFetchTask'];
        yield 'registerPushTask' => ['registerPushTask'];
        yield 'registerNotificationAction' => ['registerNotificationAction'];
        yield 'structuredPushNotificationSupport' => ['structuredPushNotificationSupport'];
        yield 'simplePushNotificationSupport' => ['simplePushNotificationSupport'];
        yield 'registerPeriodicSyncTask' => ['registerPeriodicSyncTask'];
        yield 'notifyPeriodicSyncClients' => ['notifyPeriodicSyncClients'];
    }

    #[Test]
    public function itRunsRightAfterTheWorkboxImport(): void
    {
        $attributes = (new ReflectionClass(WorkboxHelpers::class))->getAttributes(AsTaggedItem::class);

        static::assertCount(1, $attributes);
        static::assertSame(1023, $attributes[0]->newInstance()->priority);
    }

    private function createRule(Workbox $workbox): WorkboxHelpers
    {
        $serviceWorker = new ServiceWorker();
        $serviceWorker->workbox = $workbox;

        $denormalizer = $this->createMock(DenormalizerInterface::class);
        $denormalizer
            ->method('denormalize')
            ->willReturn($serviceWorker);

        $serviceWorkerBuilder = new ServiceWorkerBuilder($denormalizer, []);

        return new WorkboxHelpers($serviceWorkerBuilder);
    }
}
