<?php

declare(strict_types=1);

namespace SpomkyLabs\PwaBundle\Tests\Functional;

use const JSON_THROW_ON_ERROR;
use PHPUnit\Framework\Attributes\Test;
use SpomkyLabs\PwaBundle\Service\FaviconsCompiler;
use SpomkyLabs\PwaBundle\Service\ManifestCompiler;
use SpomkyLabs\PwaBundle\Service\ServiceWorkerCompiler;
use SpomkyLabs\PwaBundle\Twig\PwaRuntime;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestStack;

/**
 * When the application is not served from the root of the domain, e.g. http://localhost/MyProject/, every
 * public URL generated by the bundle must be prefixed with the base path.
 *
 * @see https://github.com/Spomky-Labs/pwa-bundle/issues/442
 *
 * @internal
 */
final class BasePathTest extends KernelTestCase
{
    private const BASE_PATH = '/MyProject';

    #[Test]
    public function theManifestAndTheServiceWorkerAreDeclaredWithTheBasePath(): void
    {
        // Given
        self::bootKernel();
        $this->pushRequestWithBasePath();
        $runtime = self::getContainer()->get(PwaRuntime::class);
        static::assertInstanceOf(PwaRuntime::class, $runtime);

        // When
        $output = $runtime->load();

        // Then
        static::assertStringContainsString('<link rel="manifest" href="/MyProject/site.webmanifest"', $output);
        static::assertStringContainsString("new workbox.Workbox('/MyProject/sw.js'", $output);
        static::assertStringContainsString("script.src = '/MyProject/workbox/workbox-window.prod.umd.js'", $output);
    }

    #[Test]
    public function theFaviconsAreDeclaredWithTheBasePath(): void
    {
        // Given
        self::bootKernel();
        $this->pushRequestWithBasePath();
        $compiler = self::getContainer()->get(FaviconsCompiler::class);
        static::assertInstanceOf(FaviconsCompiler::class, $compiler);

        // When
        $html = '';
        $urls = [];
        foreach ($compiler->getFiles() as $file) {
            $html .= $file->html ?? '';
            $urls[] = $file->url;
        }

        // Then
        static::assertStringContainsString('href="/MyProject/favicon.ico"', $html);
        static::assertStringNotContainsString('href="/favicon.ico"', $html);

        // The URL of the file itself is the path it is written to: it must not contain the base path.
        static::assertContains('/favicon.ico', $urls);
    }

    #[Test]
    public function theWorkboxScriptsAreImportedWithTheBasePath(): void
    {
        // Given
        self::bootKernel();
        $this->pushRequestWithBasePath();
        $compiler = self::getContainer()->get(ServiceWorkerCompiler::class);
        static::assertInstanceOf(ServiceWorkerCompiler::class, $compiler);

        // When
        $serviceWorker = null;
        foreach ($compiler->getFiles() as $file) {
            if ($file->url === '/sw.js') {
                $serviceWorker = $file->getData();
            }
        }

        // Then
        static::assertIsString($serviceWorker);
        static::assertStringContainsString("importScripts('/MyProject/workbox/workbox-sw.js')", $serviceWorker);
        static::assertStringContainsString("importScripts('/MyProject/idb/umd.js')", $serviceWorker);
        static::assertStringContainsString(
            "workbox.setConfig({modulePathPrefix: '/MyProject/workbox'})",
            $serviceWorker
        );
    }

    #[Test]
    public function theManifestResourcesUseTheBasePath(): void
    {
        // Given
        self::bootKernel();
        $this->pushRequestWithBasePath();
        $compiler = self::getContainer()->get(ManifestCompiler::class);
        static::assertInstanceOf(ManifestCompiler::class, $compiler);

        // When
        $manifest = null;
        foreach ($compiler->getFiles() as $file) {
            $manifest = json_decode($file->getData(), true, flags: JSON_THROW_ON_ERROR);
        }

        // Then
        static::assertIsArray($manifest);
        static::assertSame('/MyProject/sw.js', $manifest['serviceworker']['src']);
        foreach ($manifest['icons'] as $icon) {
            static::assertStringStartsWith('/MyProject/', $icon['src']);
        }
    }

    #[Test]
    public function noBasePathIsAddedWhenTheApplicationIsServedFromTheRoot(): void
    {
        // Given
        self::bootKernel();
        $requestStack = self::getContainer()->get(RequestStack::class);
        static::assertInstanceOf(RequestStack::class, $requestStack);
        $requestStack->push(Request::create('/'));
        $runtime = self::getContainer()->get(PwaRuntime::class);
        static::assertInstanceOf(PwaRuntime::class, $runtime);

        // When
        $output = $runtime->load();

        // Then
        static::assertStringContainsString('<link rel="manifest" href="/site.webmanifest"', $output);
        static::assertStringContainsString("new workbox.Workbox('/sw.js'", $output);
    }

    private function pushRequestWithBasePath(): void
    {
        $requestStack = self::getContainer()->get(RequestStack::class);
        static::assertInstanceOf(RequestStack::class, $requestStack);
        $request = Request::create(self::BASE_PATH . '/', server: [
            'SCRIPT_FILENAME' => self::BASE_PATH . '/index.php',
            'SCRIPT_NAME' => self::BASE_PATH . '/index.php',
            'PHP_SELF' => self::BASE_PATH . '/index.php',
        ]);
        static::assertSame(self::BASE_PATH, $request->getBasePath());
        $requestStack->push($request);
    }
}
