<?php

declare(strict_types=1);

namespace SpomkyLabs\PwaBundle\ServiceWorkerRule;

use SpomkyLabs\PwaBundle\Dto\Workbox;
use SpomkyLabs\PwaBundle\Service\ServiceWorkerBuilder;
use Symfony\Component\DependencyInjection\Attribute\AsTaggedItem;

/**
 * Helpers the application cannot replace with a plain "self.addEventListener()".
 *
 * A helper belongs here only when it arbitrates an order between several rules
 * generated by the bundle, or carries a state shared between them. Everything else is
 * something the application writes itself in its own service worker source, and lives
 * in WorkboxDeprecatedHelpers until 2.0.0.
 */
#[AsTaggedItem(priority: 1023)]
final readonly class WorkboxHelpers implements ServiceWorkerRuleInterface
{
    private Workbox $workbox;

    public function __construct(ServiceWorkerBuilder $serviceWorkerBuilder)
    {
        $this->workbox = $serviceWorkerBuilder->create()
            ->workbox;
    }

    public function process(bool $debug = false): string
    {
        if ($this->workbox->enabled === false) {
            return '';
        }
        return <<<CUSTOM_HELPERS
function precacheResources(strategy, resourceList, event) {
  if (!(event instanceof ExtendableEvent)) {
    throw new Error("precacheResources needs a valid ExtendableEvent");
  }
  return Promise.all(resourceList.map(path =>
    strategy.handleAll({
      event,
      request: new Request(path),
    })[1]
  ));
}

function createBackgroundSyncPlugin(queueName, maxRetentionTime = 2880, forceSyncFallback = false) {
  return new workbox.backgroundSync.BackgroundSyncPlugin(queueName, {
    maxRetentionTime,
    forceSyncFallback
  });
}

function createBackgroundSyncPluginWithBroadcast(queueName, channelName, maxRetentionTime = 2880, forceSyncFallback = false) {
  const queue = new workbox.backgroundSync.Queue(queueName, {
    maxRetentionTime,
    forceSyncFallback,
  });

  const bc = new BroadcastChannel(channelName);

  const replayQueueWithProgress = async () => {
    let entry;
    let successCount = 0;
    let failureCount = 0;
    const total = (await queue.getAll()).length;

    while ((entry = await queue.shiftRequest())) {
      try {
        await fetch(entry.request.clone());
        successCount++;
      } catch (error) {
        failureCount++;
        await queue.unshiftRequest(entry);
        throw error;
      } finally {
        const remaining = (await queue.getAll()).length;
        bc.postMessage({ name: queueName, replaying: true, remaining });
      }
    }

    const remaining = (await queue.getAll()).length;
    bc.postMessage({
      name: queueName,
      replayed: true,
      remaining,
      successCount,
      failureCount,
    });
  };

  bc.onmessage = async (event) => {
    if (event.data?.type === 'status-request') {
      const entries = await queue.getAll();
      bc.postMessage({ name: queueName, remaining: entries.length });
    }

    if (event.data?.type === 'replay-request') {
      try {
        await replayQueueWithProgress();
      } catch (error) {
        const entries = await queue.getAll();
        bc.postMessage({
          name: queueName,
          replayed: false,
          remaining: entries.length,
          error: error.message,
        });
      }
    }
  };

  return {
    fetchDidFail: async ({ request }) => {
      await queue.pushRequest({ request });
      const entries = await queue.getAll();
      bc.postMessage({ name: queueName, remaining: entries.length });
    },
    onSync: async () => {
      await replayQueueWithProgress();
    },
  };
}

const installTasks = [];
function registerInstallTask(callback, priority = 100) {
  installTasks.push({
    callback: (event) => {
      const result = callback(event);
      if (!result?.then) console.warn("Install task did not return a Promise");
      return result;
    },
    priority,
  });
}
self.addEventListener('install', (event) => {
  event.waitUntil(
    installTasks
      .sort((a, b) => a.priority - b.priority)
      .reduce(
        (chain, task) => chain.then(() => task.callback(event)),
        Promise.resolve()
      )
  );
});

function statusGuard(min, max) {
  return {
    fetchDidSucceed: ({ response }) => {
      if (response.status >= min && response.status <= max) {
        throw new Error(`Server error: \${response.status}`);
      }
      return response;
    }
  };
}

// Counterpart of the workbox-window registration injected by PwaRuntime: the page
// calls wb.messageSkipWaiting() when the user accepts the update.
self.addEventListener('message', (event) => {
  if (event.data?.type !== 'SKIP_WAITING') {
    return;
  }
  event.waitUntil(self.skipWaiting().then(() => self.clients.claim()));
});

const usedCacheNames = new Set();
function registerCacheName(name) {
  usedCacheNames.add(name);
  return name;
}

// Called on install by the cache clearing rule, with every cache name currently stored.
// Return the ones to delete. Caches opened by the application are unknown to
// registerCacheName(), so this is how they get purged.
const clearCacheListeners = [];
function registerClearCacheListener(callback) {
  clearCacheListeners.push(callback);
}
const cacheInstances = new Map();

async function openCache(name) {
  if (!cacheInstances.has(name)) {
    const cache = await caches.open(name);
    cacheInstances.set(name, cache);
  }
  return cacheInstances.get(name);
}

CUSTOM_HELPERS;
    }
}
