<?php

declare(strict_types=1);

namespace SpomkyLabs\PwaBundle\ServiceWorkerRule;

use SpomkyLabs\PwaBundle\Dto\Workbox;
use SpomkyLabs\PwaBundle\Service\ServiceWorkerBuilder;
use Symfony\Component\DependencyInjection\Attribute\AsTaggedItem;

/**
 * Helpers kept for backward compatibility only.
 *
 * They all wrap service worker events that the bundle itself never populates, so a
 * plain "self.addEventListener()" in the application's own service worker source
 * (see the "src" option) does exactly the same job without the indirection. They
 * are emitted as long as "pwa.serviceworker.workbox.keep_deprecated_helpers" is
 * true, and this whole class disappears in 2.0.0.
 *
 * The helpers that stay live in WorkboxHelpers: those arbitrate an order between
 * several rules generated by the bundle, or carry a state shared between them.
 *
 * Runs after WorkboxImport (1024), WorkboxHelpers (1023) and NavigationPreload (1022),
 * but before the rules calling these helpers: BackgroundFetchCache sits at the default
 * priority, and the application source is appended last by the compiler.
 *
 * @deprecated since 1.6.0, will be removed in 2.0.0 along with the helpers it emits. Replace
 * them with plain "self.addEventListener()" calls in your own service worker source, then set
 * "pwa.serviceworker.workbox.keep_deprecated_helpers" to false.
 */
#[AsTaggedItem(priority: 1021)]
final readonly class WorkboxDeprecatedHelpers implements ServiceWorkerRuleInterface
{
    private Workbox $workbox;

    public function __construct(ServiceWorkerBuilder $serviceWorkerBuilder)
    {
        $this->workbox = $serviceWorkerBuilder->create()
            ->workbox;
    }

    public function process(bool $debug = false): string
    {
        if ($this->workbox->enabled === false || $this->workbox->keepDeprecatedHelpers === false) {
            return '';
        }
        $bgFetchDbName = $this->workbox->backgroundFetch !== null ? $this->workbox->backgroundFetch->dbName : 'background-fetch-db';

        $declaration = '';
        if ($debug) {
            $declaration .= <<<DEBUG_COMMENT


/**************************************************** DEPRECATED HELPERS ****************************************************/
// Deprecated since 1.6.0, removed in 2.0.0.
// Set "pwa.serviceworker.workbox.keep_deprecated_helpers" to false to stop emitting them.

DEBUG_COMMENT;
        }

        return $declaration . <<<DEPRECATED_HELPERS
const reportedDeprecations = new Set();
function reportDeprecatedHelper(name, replacement) {
  if (reportedDeprecations.has(name)) {
    return;
  }
  reportedDeprecations.add(name);
  console.warn(`[pwa-bundle] \${name}() is deprecated since 1.6.0 and will be removed in 2.0.0. \${replacement}`);
}

function registerCacheFirst(routeMatchFn, cacheName, plugins = []) {
  reportDeprecatedHelper('registerCacheFirst', 'Build the strategy and call workbox.routing.registerRoute() directly.');
  const strategy = new workbox.strategies.CacheFirst({ cacheName, plugins });
  workbox.routing.registerRoute(routeMatchFn, strategy);
  return strategy;
}

const messageTasks = [];
function registerMessageTask(callback) {
  reportDeprecatedHelper('registerMessageTask', 'Use self.addEventListener("message", (event) => event.waitUntil(...)).');
  messageTasks.push(callback);
}

self.addEventListener('message', (event) => {
  event.waitUntil(
    messageTasks.reduce(
      (chain, task) => chain.then(() => task(event)),
      Promise.resolve()
    )
  );
});

async function openBackgroundFetchDatabase() {
  reportDeprecatedHelper('openBackgroundFetchDatabase', 'Open your own database with self.idb.openDB(), which stays available.');
  return await self.idb.openDB('{$bgFetchDbName}', 1, {
    upgrade(db) {
      if (!db.objectStoreNames.contains('files')) {
        db.createObjectStore('files', { keyPath: 'id' });
      }

      if (!db.objectStoreNames.contains('chunks')) {
        const store = db.createObjectStore('chunks', { keyPath: ['id', 'index'] });
        store.createIndex('by-id', 'id');
      } else {
        const store = db.transaction.objectStore('chunks');
        if (!Array.from(store.indexNames).includes('by-id')) {
          store.createIndex('by-id', 'id');
        }
      }
    }
  });
}

const bgFetchMetadata = new Map();
const bgFetchChannel = new BroadcastChannel('bg-fetch');
bgFetchChannel.onmessage = async (event) => {
  const { type, id, meta } = event.data || {};

  switch (type) {
    case 'register-meta':
      bgFetchMetadata.set(id, meta);
      break;

    case 'get-meta':
      const metadata = bgFetchMetadata.get(id) || null;
      bgFetchChannel.postMessage({ type: 'meta-response', id, metadata });
      break;

    case 'clear-meta':
      bgFetchMetadata.delete(id);
      break;

    case 'list-stored-files':
      {
        const db = await openBackgroundFetchDatabase();
        const files = await db.getAll('files');
        bgFetchChannel.postMessage({ type: 'stored-files', files });
        break;
      }

    case 'delete-stored-file':
      {
        const name = event.data.name;
        const db = await openBackgroundFetchDatabase();
        const allFiles = await db.getAll('files');
        const target = allFiles.find(f => f.name === name);
        if (target) {
          await db.delete('files', target.id);
          let index = 0;
          while (await db.get('chunks', [target.id, index])) {
            await db.delete('chunks', [target.id, index++]);
          }
        }
        break;
      }
  }
};

const backgroundFetchTasks = {
  click: [],
  success: [],
  fail: [],
};
function registerBackgroundFetchTask(type, callback, priority = 100) {
  reportDeprecatedHelper('registerBackgroundFetchTask', 'Use self.addEventListener("backgroundfetchsuccess", ...) and its siblings.');
  if (!backgroundFetchTasks[type]) {
    throw new Error(`Unknown background fetch event type: \${type}`);
  }

  backgroundFetchTasks[type].push({
    callback: (event) => {
      const result = callback(event);
      if (!result?.then) {
        console.warn(`[\${type}] task did not return a Promise`);
      }
      return result;
    },
    priority,
  });
}

function runBackgroundFetchTasks(type, event) {
  const tasks = backgroundFetchTasks[type] ?? [];
  return tasks
    .sort((a, b) => a.priority - b.priority)
    .reduce(
      (chain, task) => chain.then(() => task.callback(event)),
      Promise.resolve()
    );
}

self.addEventListener('backgroundfetchclick', (event) => {
  event.waitUntil(runBackgroundFetchTasks('click', event));
});

self.addEventListener('backgroundfetchsuccess', (event) => {
  event.waitUntil(runBackgroundFetchTasks('success', event));
});

self.addEventListener('backgroundfetchfail', (event) => {
  event.waitUntil(runBackgroundFetchTasks('fail', event));
});

const pushTasks = [];
function registerPushTask(callback) {
  reportDeprecatedHelper('registerPushTask', 'Use self.addEventListener("push", (event) => event.waitUntil(...)).');
  pushTasks.push(callback);
}
self.addEventListener('push', (event) => {
    if (typeof self.Notification !== 'undefined' && self.Notification.permission === 'denied') {
        return;
    }
    event.waitUntil(
      pushTasks.reduce(
        (chain, task) => chain.then(() => task(event)),
        Promise.resolve()
      )
    );
});

const notificationActionHandlers = new Map();
function registerNotificationAction(actionName, handler) {
  reportDeprecatedHelper('registerNotificationAction', 'Use self.addEventListener("notificationclick", ...) and switch on event.action.');
  notificationActionHandlers.set(actionName, handler);
}
self.addEventListener('notificationclick', event => {
  event.notification.close();
  const action = event.action || "";
  const promises = [];

  const specificHandler = notificationActionHandlers.get(action);
  if (typeof specificHandler === 'function') {
    promises.push(Promise.resolve(specificHandler(event)));
  }

  const wildcardHandler = notificationActionHandlers.get('*');
  if (typeof wildcardHandler === 'function') {
    promises.push(Promise.resolve(wildcardHandler(event)));
  }

  if (promises.length > 0) {
    event.waitUntil(Promise.all(promises));
  }
});
const structuredPushNotificationSupport = (event) => {
  reportDeprecatedHelper('structuredPushNotificationSupport', 'Parse the payload and call self.registration.showNotification() yourself.');
  const {data} = event;
  const sendNotification = response => {
    const {title, options} = JSON.parse(response);
    return self.registration.showNotification(title, options);
  };

  if (data) {
    const message = data.text();
    event.waitUntil(sendNotification(message));
  }
}
function simplePushNotificationSupport(event) {
  reportDeprecatedHelper('simplePushNotificationSupport', 'Parse the payload and call self.registration.showNotification() yourself.');
  const { data } = event;

  if (!data) return;

  const message = data.text();
  const sendNotification = (text) => {
    return self.registration.showNotification('Notification', {
      body: text
    });
  };

  event.waitUntil(sendNotification(message));
}

const periodicSyncTasks = new Map();

function registerPeriodicSyncTask(tag, callback, priority = 100) {
  reportDeprecatedHelper('registerPeriodicSyncTask', 'Use self.addEventListener("periodicsync", ...) and switch on event.tag.');
  if (!periodicSyncTasks.has(tag)) {
    periodicSyncTasks.set(tag, []);
  }
  periodicSyncTasks.get(tag).push({
    priority,
    callback: (event) => {
      const result = callback(event);
      if (!result?.then) console.warn(`[\${tag}] periodic sync task did not return a Promise`);
      return result;
    }
  });
}

async function runPeriodicSyncTasks(tag, event) {
  const tasks = periodicSyncTasks.get(tag) ?? [];
  return tasks
    .sort((a, b) => a.priority - b.priority)
    .reduce(
      (chain, task) => chain.then(() => task.callback(event)),
      Promise.resolve()
    );
}

self.addEventListener('periodicsync', event => {
  event.waitUntil(runPeriodicSyncTasks(event.tag, event));
});

const periodicChannel = new BroadcastChannel('periodic-sync');

function notifyPeriodicSyncClients(tag, payload = {}) {
  reportDeprecatedHelper('notifyPeriodicSyncClients', 'Create your own BroadcastChannel and post to it.');
  periodicChannel.postMessage({
    type: 'periodic-sync-update',
    tag,
    timestamp: Date.now(),
    ...payload
  });
}

DEPRECATED_HELPERS;
    }
}
