<?php

declare(strict_types=1);

use Symfony\Component\Config\Definition\Configurator\DefinitionConfigurator;

return static function (DefinitionConfigurator $definition): void {
    $definition->rootNode()
        ->children()
        ->arrayNode('resource_hints')
        ->info('Resource Hints configuration for preconnect, dns-prefetch, and preload.')
        ->canBeEnabled()
        ->children()
        ->booleanNode('auto_preconnect')
        ->defaultTrue()
        ->info('Automatically add preconnect hints for detected external origins (Workbox CDN, Google Fonts).')
        ->end()
        ->arrayNode('preconnect')
        ->info('Additional origins to preconnect to (establishes early connection: DNS + TCP + TLS).')
        ->scalarPrototype()
        ->end()
        ->example(['https://api.example.com', 'https://cdn.example.com'])
        ->end()
        ->arrayNode('dns_prefetch')
        ->info('Additional origins for DNS prefetch only (DNS resolution only, lighter than preconnect).')
        ->scalarPrototype()
        ->end()
        ->example(['https://analytics.example.com'])
        ->end()
        ->arrayNode('preload')
        ->info('Resources to preload (downloaded early with high priority).')
        ->arrayPrototype()
        ->children()
        ->scalarNode('href')
        ->isRequired()
        ->info('The URL or path to preload.')
        ->example('/fonts/custom-font.woff2')
        ->end()
        ->enumNode('as')
        ->isRequired()
        ->values(['script', 'style', 'font', 'image', 'fetch', 'document', 'audio', 'video', 'track', 'worker'])
        ->info('The resource type.')
        ->end()
        ->scalarNode('type')
        ->defaultNull()
        ->info('The MIME type of the resource.')
        ->example('font/woff2')
        ->end()
        ->enumNode('crossorigin')
        ->values(['anonymous', 'use-credentials'])
        ->defaultNull()
        ->info('The crossorigin attribute value. Required for fonts.')
        ->end()
        ->enumNode('fetchpriority')
        ->values(['high', 'low', 'auto'])
        ->defaultNull()
        ->info('The fetch priority hint.')
        ->end()
        ->scalarNode('media')
        ->defaultNull()
        ->info('Media query for responsive preloading.')
        ->example('(min-width: 768px)')
        ->end()
        ->end()
        ->end()
        ->end()
        ->end()
        ->end()
        ->end()
        ->end();
};
