<?php

declare(strict_types=1);

use Symfony\Component\Config\Definition\Configurator\DefinitionConfigurator;

return static function (DefinitionConfigurator $definition): void {
    $definition->rootNode()
        ->children()
        ->arrayNode('speculation_rules')
        ->info('Speculation Rules API configuration for prefetching and prerendering pages.')
        ->canBeEnabled()
        ->children()
        ->arrayNode('prefetch')
        ->info('Rules for prefetching resources (download but do not execute).')
        ->arrayPrototype()
        ->children()
        ->enumNode('source')
        ->values(['list', 'document'])
        ->defaultValue('document')
        ->info('The source type: "list" for explicit URLs, "document" for link matching.')
        ->end()
        ->arrayNode('urls')
        ->info('For "list" source: explicit URLs to prefetch.')
        ->arrayPrototype()
        ->beforeNormalization()
        ->ifString()
        ->then(static fn (string $v): array => [
            'path' => $v,
        ])
        ->end()
        ->children()
        ->scalarNode('path')
        ->isRequired()
        ->info('The URL path or route name.')
        ->end()
        ->arrayNode('params')
        ->treatFalseLike([])
        ->treatTrueLike([])
        ->treatNullLike([])
        ->prototype('variable')
        ->end()
        ->info('Route parameters if path is a route name.')
        ->end()
        ->end()
        ->end()
        ->end()
        ->scalarNode('selector_matches')
        ->defaultNull()
        ->info('For "document" source: CSS selector to match links.')
        ->example('a.prefetch, a[data-prefetch]')
        ->end()
        ->scalarNode('href_matches')
        ->defaultNull()
        ->info('For "document" source: URL pattern to match href attributes.')
        ->example('/products/*')
        ->end()
        ->enumNode('eagerness')
        ->values(['immediate', 'eager', 'moderate', 'conservative'])
        ->defaultValue('moderate')
        ->info(
            'Eagerness level: "immediate" (viewport), "eager" (hover 200ms), "moderate" (hover 100ms), "conservative" (mousedown/touchstart).'
        )
        ->end()
        ->scalarNode('referrer_policy')
        ->defaultNull()
        ->info('Referrer policy for the speculative request.')
        ->example('no-referrer-when-downgrade')
        ->end()
        ->end()
        ->end()
        ->end()
        ->arrayNode('prerender')
        ->info('Rules for prerendering pages (download and execute in hidden context). Use with caution.')
        ->arrayPrototype()
        ->children()
        ->enumNode('source')
        ->values(['list', 'document'])
        ->defaultValue('document')
        ->info('The source type: "list" for explicit URLs, "document" for link matching.')
        ->end()
        ->arrayNode('urls')
        ->info('For "list" source: explicit URLs to prerender.')
        ->arrayPrototype()
        ->beforeNormalization()
        ->ifString()
        ->then(static fn (string $v): array => [
            'path' => $v,
        ])
        ->end()
        ->children()
        ->scalarNode('path')
        ->isRequired()
        ->info('The URL path or route name.')
        ->end()
        ->arrayNode('params')
        ->treatFalseLike([])
        ->treatTrueLike([])
        ->treatNullLike([])
        ->prototype('variable')
        ->end()
        ->info('Route parameters if path is a route name.')
        ->end()
        ->end()
        ->end()
        ->end()
        ->scalarNode('selector_matches')
        ->defaultNull()
        ->info('For "document" source: CSS selector to match links.')
        ->example('a.prerender, a[data-prerender]')
        ->end()
        ->scalarNode('href_matches')
        ->defaultNull()
        ->info('For "document" source: URL pattern to match href attributes.')
        ->example('/checkout')
        ->end()
        ->enumNode('eagerness')
        ->values(['immediate', 'eager', 'moderate', 'conservative'])
        ->defaultValue('conservative')
        ->info('Eagerness level. For prerender, "conservative" is recommended.')
        ->end()
        ->scalarNode('referrer_policy')
        ->defaultNull()
        ->info('Referrer policy for the speculative request.')
        ->end()
        ->end()
        ->end()
        ->end()
        ->end()
        ->end()
        ->end()
        ->end();
};
