name: "Infection"

on:
  push:
    branches:
      - "*.x"

jobs:
  mutation_testing:
    name: "0️⃣ Mutation Testing"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/spomky-labs/phpqa:8.4
    env:
      XDEBUG_MODE: coverage
    steps:
      - uses: actions/checkout@v4

      - uses: ramsey/composer-install@v3
        with:
          dependency-versions: highest
          composer-options: --optimize-autoloader

      - name: Restore PHPUnit result cache
        uses: actions/cache@v4
        with:
          path: .phpunit.cache
          key: phpunit-cache-${{ hashFiles('composer.lock') }}

      - name: "Execute Infection"
        run: infection --min-msi=35 --min-covered-msi=80 --threads=max --logger-github -s --configuration=.ci-tools/infection.json.dist
